### ISSUE TITLE
SPI Settings in All Branch's

### ISSUE THREAD

**Issue by Donziboy2** [KurtE/ILI9341_t3n#5]
Kurt is the below correct?
I would expect the K to be faster then the non K?

#ifdef KINETISK
#define ILI9341_SPICLOCK 30000000               //This affects T3.6
#define ILI9341_SPICLOCK_READ 2000000      //2MHz
#else
#define ILI9341_SPICLOCK 30000000
#define ILI9341_SPICLOCK_READ 20000000   //20MHz
#endif

**Comment by KurtE** [comment]
Probably not - The T-LC support is experimental.  The ILI9341_t3 had no support for LC, but since I added support in SPIN for some stuff thought it would be interesting to see if it could work on the LC.  

Probably at a minimum the 20M for read on LC should be 2M like the K... 

Also remember this is not necessarily the speed we get but the speed we ask for.  It is then up to SPI to come up with the actual clock which should not exceed this speed...
